python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/learning_rate - linear scale up/0.0001/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/learning_rate - linear scale up/0.0002/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/learning_rate - linear scale up/0.0003/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/learning_rate - linear scale up/0.0004/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/learning_rate - linear scale up/0.0005/" --erp_degree 1 --filter_band hidelta --plot_hist True

python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.01/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.02/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.03/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.04/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.05/" --erp_degree 1 --filter_band hidelta --plot_hist True


python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/pain_vs_wd/learning_rate - linear scale up/0.0001/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/pain_vs_wd/learning_rate - linear scale up/0.0002/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/pain_vs_wd/learning_rate - linear scale up/0.0003/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/pain_vs_wd/learning_rate - linear scale up/0.0004/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/pain_vs_wd/learning_rate - linear scale up/0.0005/" --erp_degree 1 --filter_band hidelta --plot_hist True

python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.01/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.02/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.03/" --erp_degree 1 --filter_band hidelta --plot_hist True
# python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.04/" --erp_degree 1 --filter_band hidelta --plot_hist True
# python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.05/" --erp_degree 1 --filter_band hidelta --plot_hist True


python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/learning_rate - linear scale up/0.0001/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/learning_rate - linear scale up/0.0002/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/learning_rate - linear scale up/0.0003/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/learning_rate - linear scale up/0.0004/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/learning_rate - linear scale up/0.0005/" --erp_degree 1 --filter_band hidelta --plot_hist True

python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.01/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.02/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.03/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.04/" --erp_degree 1 --filter_band hidelta --plot_hist True
python3 ../scripts/Run_eval_cnn.py erps --study_names CU_pain CU_control glynn_pain lyons_pain_2 WD_31-40 WD_41-50 WD_51-60 --log_dir "/wavi/WAViMedEEG/logs/rehab_vs_wd/regularization_parameter - linear scale up/0.05/" --erp_degree 1 --filter_band hidelta --plot_hist True
